apiVersion: v1
kind: Service
metadata:
    name: postgres-db-external
    labels:
        app: postgres-db
spec:
    type: NodePort
    selector:
        app: postgres-db
    ports:
        - port: 5432
          targetPort: 5432

---
apiVersion: v1
kind: Service
metadata:
    name: postgres-db-internal
    labels:
        app: postgres-db
spec:
    selector:
        app: postgres-db
    ports:
        - port: 5432
          targetPort: 5432

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
    name: postgres-db
spec:
    selector:
        matchLabels:
            app: postgres-db
    serviceName: 'postgres-db-service'
    replicas: 1
    minReadySeconds: 10
    template:
        metadata:
            labels:
                app: postgres-db
        spec:
            terminationGracePeriodSeconds: 10
            containers:
                - name: postgres
                  image: postgres:latest
                  ports:
                      - containerPort: 8080
                        name: web
                  volumeMounts:
                      - name: postgres-db-disk
                        mountPath: /data
                  envFrom:
                      - configMapRef:
                            name: postgres-config
    volumeClaimTemplates:
        - metadata:
              name: postgres-db-disk
          spec:
              accessModes: ['ReadWriteOnce']
              storageClassName: 'manual'
              resources:
                  requests:
                      storage: 8Gi
              volumeName: postgresdb-pv
