apiVersion: v1
kind: Pod 
metadata:
  name: core
spec:
  containers:
  - name: core
    image: nicomatex/fiubook_core:latest
    ports:
      - containerPort: 3000
        name: http
    resources:
      requests:
        ephemeral-storage: "1Gi"
      limits:
        ephemeral-storage: "1Gi"