apiVersion: v1
kind: ConfigMap
metadata:
    name: postgres-config
    labels:
        app: postgres-db
data:
    POSTGRES_DB: postgres
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: pistacho
    PGDATA: /data/pgdata
